// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdiSg5NepicyHvQdSr1ebOWglxwNrdj2w',
    appId: '1:30395731406:web:986a4c94af6abc19cc2f9f',
    messagingSenderId: '30395731406',
    projectId: 'pbm-1ecb7',
    authDomain: 'pbm-1ecb7.firebaseapp.com',
    storageBucket: 'pbm-1ecb7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBYnPBD8-3jnZ56v3PSowqZR0XSuTnmT8',
    appId: '1:30395731406:android:4d6df9b1cabc1b3fcc2f9f',
    messagingSenderId: '30395731406',
    projectId: 'pbm-1ecb7',
    storageBucket: 'pbm-1ecb7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuyX0UfyyFmjzYU0s34z7hgdpTC_G_0Ck',
    appId: '1:30395731406:ios:78f2f9006d810a3acc2f9f',
    messagingSenderId: '30395731406',
    projectId: 'pbm-1ecb7',
    storageBucket: 'pbm-1ecb7.appspot.com',
    iosClientId: '30395731406-oiqd497opgcl2bnki49m06v8kbs28v25.apps.googleusercontent.com',
    iosBundleId: 'com.example.pbm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuyX0UfyyFmjzYU0s34z7hgdpTC_G_0Ck',
    appId: '1:30395731406:ios:78f2f9006d810a3acc2f9f',
    messagingSenderId: '30395731406',
    projectId: 'pbm-1ecb7',
    storageBucket: 'pbm-1ecb7.appspot.com',
    iosClientId: '30395731406-oiqd497opgcl2bnki49m06v8kbs28v25.apps.googleusercontent.com',
    iosBundleId: 'com.example.pbm',
  );
}
